Installed sct
- To fix error:

```
Building
Build failed.
The Broccoli Plugin: [] failed with:
Error: Cannot find module 'cst'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/MichalBryxi/ember-dag-generator/node_modules/ember-suave/node_modules/jscs-ember-deprecations/lib/rules/disallow-emberkeys.js:2:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (/home/travis/build/MichalBryxi/ember-dag-generator/node_modules/ember-suave/node_modules/jscs-ember-deprecations/lib/index.js:12:30)
    at NodeConfiguration.Configuration._loadPlugin (/home/travis/build/MichalBryxi/ember-dag-generator/node_modules/ember-suave/node_modules/jscs/lib/config/configuration.js:499:5)
    at NodeConfiguration._loadPlugin (/home/travis/build/MichalBryxi/ember-dag-generator/node_modules/ember-suave/node_modules/jscs/lib/config/node-configuration.js:135:48)
    at NodeConfiguration.<anonymous> (/home/travis/build/MichalBryxi/ember-dag-generator/node_modules/ember-suave/node_modules/jscs/lib/config/configuration.js:438:18)
    at Array.forEach (native)
```